name: Update Navigation Data
description: Updates Navigation Data and creates a Pull Request.

on:
  workflow_dispatch:

jobs:
  update-and-pull-request:

    runs-on: ubuntu-latest

    # Install deps
    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v4

      - name: 🎚️ Enable Corepack
        run: corepack enable

      - name: 🏗️ Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: 📦 Install deps
        run: yarn install --immutable

      # Create new branch
#      - name: Git
#        run: |
#          git --version
#          git config --global user.name 'GitHub Actions Bot'
#          git config --global user.email '<>'
#          git status
#          git checkout main
#          git checkout -b update-navigation-data
          
      # Run script
#      - name: Run script
#        uses: actions/github-script@v8
#        with:
#          script: |
#            node ./scripts/navigation-codegen.js
      - name: Run script
        run: yarn run nav:codegen
      
      # Add and commit
      # Push changes (?)
#      - name: Git
#        run: |
#          git add .
#          git commit -m "chore: updated navigation data"
#          git push -u origin update-navigation-data

      # Create new PR based on branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
#        with:
#          base: update-navigation-data
#          branch: main











        
